FROM python:3.7.12

WORKDIR /app

COPY ./requirements.txt /app/requirements.txt

RUN /usr/local/bin/python -m pip install --upgrade pip

# RUN pip install -r /app/requirements.txt

RUN pip install numpy
RUN pip install qdrant_client
RUN pip install pymysql
RUN pip install sentence_transformers
RUN pip install torch
RUN pip install tqdm
RUN pip install uvicorn
RUN pip install fastapi
RUN pip install python-dotenv

RUN pip freeze --all > /app/requirements.txt


